//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.21 at 12:09:50 PM PST 
//


package pssg.poc.common.model.icbcDisputeBundle.eVT;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnforcementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnforcementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OfficerNumber1" type="{http://icbc.net/RSI_InformationManager}string_OfficerNumber"/>
 *         &lt;element name="DetachmentCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://icbc.net/RSI_InformationManager}string_FreeFormText">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Detachment">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://icbc.net/RSI_InformationManager}string_FreeFormText">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="OfficerName1">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://icbc.net/RSI_InformationManager}string_FreeFormText">
 *               &lt;maxLength value="79"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="WitnessingOfficerID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://icbc.net/RSI_InformationManager}string_FreeFormText">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="WitnessingOfficerName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://icbc.net/RSI_InformationManager}string_FreeFormText">
 *               &lt;maxLength value="79"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnforcementType", propOrder = {
    "officerNumber1",
    "detachmentCode",
    "detachment",
    "officerName1",
    "witnessingOfficerID",
    "witnessingOfficerName"
})
public class EnforcementType {

    @XmlElement(name = "OfficerNumber1", required = true)
    protected String officerNumber1;
    @XmlElement(name = "DetachmentCode", required = true)
    protected String detachmentCode;
    @XmlElement(name = "Detachment", required = true)
    protected String detachment;
    @XmlElement(name = "OfficerName1", required = true)
    protected String officerName1;
    @XmlElementRef(name = "WitnessingOfficerID", type = JAXBElement.class, required = false)
    protected JAXBElement<String> witnessingOfficerID;
    @XmlElementRef(name = "WitnessingOfficerName", type = JAXBElement.class, required = false)
    protected JAXBElement<String> witnessingOfficerName;

    /**
     * Gets the value of the officerNumber1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficerNumber1() {
        return officerNumber1;
    }

    /**
     * Sets the value of the officerNumber1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficerNumber1(String value) {
        this.officerNumber1 = value;
    }

    /**
     * Gets the value of the detachmentCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetachmentCode() {
        return detachmentCode;
    }

    /**
     * Sets the value of the detachmentCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetachmentCode(String value) {
        this.detachmentCode = value;
    }

    /**
     * Gets the value of the detachment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDetachment() {
        return detachment;
    }

    /**
     * Sets the value of the detachment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDetachment(String value) {
        this.detachment = value;
    }

    /**
     * Gets the value of the officerName1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfficerName1() {
        return officerName1;
    }

    /**
     * Sets the value of the officerName1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfficerName1(String value) {
        this.officerName1 = value;
    }

    /**
     * Gets the value of the witnessingOfficerID property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWitnessingOfficerID() {
        return witnessingOfficerID;
    }

    /**
     * Sets the value of the witnessingOfficerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWitnessingOfficerID(JAXBElement<String> value) {
        this.witnessingOfficerID = value;
    }

    /**
     * Gets the value of the witnessingOfficerName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWitnessingOfficerName() {
        return witnessingOfficerName;
    }

    /**
     * Sets the value of the witnessingOfficerName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWitnessingOfficerName(JAXBElement<String> value) {
        this.witnessingOfficerName = value;
    }

}
