//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.21 at 12:09:50 PM PST 
//


package pssg.poc.common.model.icbcDisputeBundle.eVT;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pssg.poc.common.model.icbcDisputeBundle.eVT package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CreateContraventionRequest_QNAME = new QName("http://icbc.net/RSI_InformationManager", "createContraventionRequest");
    private final static QName _AddressTypeJurisdiction_QNAME = new QName("", "Jurisdiction");
    private final static QName _AddressTypeStreetAddress_QNAME = new QName("", "StreetAddress");
    private final static QName _AddressTypePostalCode_QNAME = new QName("", "PostalCode");
    private final static QName _AddressTypeCity_QNAME = new QName("", "City");
    private final static QName _CreateContraventionRequestVehicle_QNAME = new QName("", "Vehicle");
    private final static QName _VehicleLicenseTypeNumber_QNAME = new QName("", "Number");
    private final static QName _IndividualPartyTypeYoungPerson_QNAME = new QName("", "YoungPerson");
    private final static QName _IndividualPartyTypeGivenName1_QNAME = new QName("", "GivenName1");
    private final static QName _IndividualPartyTypeGivenName3_QNAME = new QName("", "GivenName3");
    private final static QName _IndividualPartyTypeDriverLicense_QNAME = new QName("", "DriverLicense");
    private final static QName _IndividualPartyTypeGivenName2_QNAME = new QName("", "GivenName2");
    private final static QName _IndividualPartyTypeChangeOfAddressFlag_QNAME = new QName("", "ChangeOfAddressFlag");
    private final static QName _IndividualPartyTypeResidenceAddress_QNAME = new QName("", "ResidenceAddress");
    private final static QName _IndividualPartyTypeGender_QNAME = new QName("", "Gender");
    private final static QName _IndividualPartyTypeBirthDate_QNAME = new QName("", "BirthDate");
    private final static QName _VehicleTypeYear_QNAME = new QName("", "Year");
    private final static QName _VehicleTypeAccident_QNAME = new QName("", "Accident");
    private final static QName _VehicleTypeVehicleLicense_QNAME = new QName("", "VehicleLicense");
    private final static QName _VehicleTypeTypeCode_QNAME = new QName("", "TypeCode");
    private final static QName _VehicleTypeMakeCode_QNAME = new QName("", "MakeCode");
    private final static QName _VehicleTypeRegisteredOwnerName_QNAME = new QName("", "RegisteredOwnerName");
    private final static QName _VehicleTypeColour_QNAME = new QName("", "Colour");
    private final static QName _VehicleTypeNSC_QNAME = new QName("", "NSC");
    private final static QName _NscTypeRegistrationCode_QNAME = new QName("", "RegistrationCode");
    private final static QName _DriverLicenseTypeLicenseProduced_QNAME = new QName("", "LicenseProduced");
    private final static QName _DriverLicenseTypeExpiryYear_QNAME = new QName("", "ExpiryYear");
    private final static QName _JurisdictionTypeCode_QNAME = new QName("", "Code");
    private final static QName _CountTypeCountNumber_QNAME = new QName("", "CountNumber");
    private final static QName _EnforcementTypeWitnessingOfficerName_QNAME = new QName("", "WitnessingOfficerName");
    private final static QName _EnforcementTypeWitnessingOfficerID_QNAME = new QName("", "WitnessingOfficerID");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pssg.poc.common.model.icbcDisputeBundle.eVT
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CreateContraventionRequest }
     * 
     */
    public CreateContraventionRequest createCreateContraventionRequest() {
        return new CreateContraventionRequest();
    }

    /**
     * Create an instance of {@link CreateContraventionResponse }
     * 
     */
    public CreateContraventionResponse createCreateContraventionResponse() {
        return new CreateContraventionResponse();
    }

    /**
     * Create an instance of {@link CertificateOfServiceType }
     * 
     */
    public CertificateOfServiceType createCertificateOfServiceType() {
        return new CertificateOfServiceType();
    }

    /**
     * Create an instance of {@link EnforcementType }
     * 
     */
    public EnforcementType createEnforcementType() {
        return new EnforcementType();
    }

    /**
     * Create an instance of {@link NscType }
     * 
     */
    public NscType createNscType() {
        return new NscType();
    }

    /**
     * Create an instance of {@link VehicleType }
     * 
     */
    public VehicleType createVehicleType() {
        return new VehicleType();
    }

    /**
     * Create an instance of {@link IndividualPartyType }
     * 
     */
    public IndividualPartyType createIndividualPartyType() {
        return new IndividualPartyType();
    }

    /**
     * Create an instance of {@link CountType }
     * 
     */
    public CountType createCountType() {
        return new CountType();
    }

    /**
     * Create an instance of {@link VehicleLicenseType }
     * 
     */
    public VehicleLicenseType createVehicleLicenseType() {
        return new VehicleLicenseType();
    }

    /**
     * Create an instance of {@link ViolationType }
     * 
     */
    public ViolationType createViolationType() {
        return new ViolationType();
    }

    /**
     * Create an instance of {@link SubmissionType }
     * 
     */
    public SubmissionType createSubmissionType() {
        return new SubmissionType();
    }

    /**
     * Create an instance of {@link JurisdictionType }
     * 
     */
    public JurisdictionType createJurisdictionType() {
        return new JurisdictionType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link DriverLicenseType }
     * 
     */
    public DriverLicenseType createDriverLicenseType() {
        return new DriverLicenseType();
    }

    /**
     * Create an instance of {@link PartyType }
     * 
     */
    public PartyType createPartyType() {
        return new PartyType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateContraventionRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://icbc.net/RSI_InformationManager", name = "createContraventionRequest")
    public JAXBElement<CreateContraventionRequest> createCreateContraventionRequest(CreateContraventionRequest value) {
        return new JAXBElement<CreateContraventionRequest>(_CreateContraventionRequest_QNAME, CreateContraventionRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JurisdictionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Jurisdiction", scope = AddressType.class)
    public JAXBElement<JurisdictionType> createAddressTypeJurisdiction(JurisdictionType value) {
        return new JAXBElement<JurisdictionType>(_AddressTypeJurisdiction_QNAME, JurisdictionType.class, AddressType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StreetAddress", scope = AddressType.class)
    public JAXBElement<String> createAddressTypeStreetAddress(String value) {
        return new JAXBElement<String>(_AddressTypeStreetAddress_QNAME, String.class, AddressType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PostalCode", scope = AddressType.class)
    public JAXBElement<String> createAddressTypePostalCode(String value) {
        return new JAXBElement<String>(_AddressTypePostalCode_QNAME, String.class, AddressType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "City", scope = AddressType.class)
    public JAXBElement<String> createAddressTypeCity(String value) {
        return new JAXBElement<String>(_AddressTypeCity_QNAME, String.class, AddressType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VehicleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Vehicle", scope = CreateContraventionRequest.class)
    public JAXBElement<VehicleType> createCreateContraventionRequestVehicle(VehicleType value) {
        return new JAXBElement<VehicleType>(_CreateContraventionRequestVehicle_QNAME, VehicleType.class, CreateContraventionRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Jurisdiction", scope = VehicleLicenseType.class)
    public JAXBElement<String> createVehicleLicenseTypeJurisdiction(String value) {
        return new JAXBElement<String>(_AddressTypeJurisdiction_QNAME, String.class, VehicleLicenseType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Number", scope = VehicleLicenseType.class)
    public JAXBElement<String> createVehicleLicenseTypeNumber(String value) {
        return new JAXBElement<String>(_VehicleLicenseTypeNumber_QNAME, String.class, VehicleLicenseType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BoolYN }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "YoungPerson", scope = IndividualPartyType.class)
    public JAXBElement<BoolYN> createIndividualPartyTypeYoungPerson(BoolYN value) {
        return new JAXBElement<BoolYN>(_IndividualPartyTypeYoungPerson_QNAME, BoolYN.class, IndividualPartyType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GivenName1", scope = IndividualPartyType.class)
    public JAXBElement<String> createIndividualPartyTypeGivenName1(String value) {
        return new JAXBElement<String>(_IndividualPartyTypeGivenName1_QNAME, String.class, IndividualPartyType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GivenName3", scope = IndividualPartyType.class)
    public JAXBElement<String> createIndividualPartyTypeGivenName3(String value) {
        return new JAXBElement<String>(_IndividualPartyTypeGivenName3_QNAME, String.class, IndividualPartyType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DriverLicenseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DriverLicense", scope = IndividualPartyType.class)
    public JAXBElement<DriverLicenseType> createIndividualPartyTypeDriverLicense(DriverLicenseType value) {
        return new JAXBElement<DriverLicenseType>(_IndividualPartyTypeDriverLicense_QNAME, DriverLicenseType.class, IndividualPartyType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "GivenName2", scope = IndividualPartyType.class)
    public JAXBElement<String> createIndividualPartyTypeGivenName2(String value) {
        return new JAXBElement<String>(_IndividualPartyTypeGivenName2_QNAME, String.class, IndividualPartyType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BoolYN }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ChangeOfAddressFlag", scope = IndividualPartyType.class)
    public JAXBElement<BoolYN> createIndividualPartyTypeChangeOfAddressFlag(BoolYN value) {
        return new JAXBElement<BoolYN>(_IndividualPartyTypeChangeOfAddressFlag_QNAME, BoolYN.class, IndividualPartyType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddressType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ResidenceAddress", scope = IndividualPartyType.class)
    public JAXBElement<AddressType> createIndividualPartyTypeResidenceAddress(AddressType value) {
        return new JAXBElement<AddressType>(_IndividualPartyTypeResidenceAddress_QNAME, AddressType.class, IndividualPartyType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Gender", scope = IndividualPartyType.class)
    public JAXBElement<String> createIndividualPartyTypeGender(String value) {
        return new JAXBElement<String>(_IndividualPartyTypeGender_QNAME, String.class, IndividualPartyType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "BirthDate", scope = IndividualPartyType.class)
    public JAXBElement<XMLGregorianCalendar> createIndividualPartyTypeBirthDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_IndividualPartyTypeBirthDate_QNAME, XMLGregorianCalendar.class, IndividualPartyType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Year", scope = VehicleType.class)
    public JAXBElement<String> createVehicleTypeYear(String value) {
        return new JAXBElement<String>(_VehicleTypeYear_QNAME, String.class, VehicleType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BoolYN }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Accident", scope = VehicleType.class)
    public JAXBElement<BoolYN> createVehicleTypeAccident(BoolYN value) {
        return new JAXBElement<BoolYN>(_VehicleTypeAccident_QNAME, BoolYN.class, VehicleType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VehicleLicenseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "VehicleLicense", scope = VehicleType.class)
    public JAXBElement<VehicleLicenseType> createVehicleTypeVehicleLicense(VehicleLicenseType value) {
        return new JAXBElement<VehicleLicenseType>(_VehicleTypeVehicleLicense_QNAME, VehicleLicenseType.class, VehicleType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TypeCode", scope = VehicleType.class)
    public JAXBElement<String> createVehicleTypeTypeCode(String value) {
        return new JAXBElement<String>(_VehicleTypeTypeCode_QNAME, String.class, VehicleType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MakeCode", scope = VehicleType.class)
    public JAXBElement<String> createVehicleTypeMakeCode(String value) {
        return new JAXBElement<String>(_VehicleTypeMakeCode_QNAME, String.class, VehicleType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RegisteredOwnerName", scope = VehicleType.class)
    public JAXBElement<String> createVehicleTypeRegisteredOwnerName(String value) {
        return new JAXBElement<String>(_VehicleTypeRegisteredOwnerName_QNAME, String.class, VehicleType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Colour", scope = VehicleType.class)
    public JAXBElement<String> createVehicleTypeColour(String value) {
        return new JAXBElement<String>(_VehicleTypeColour_QNAME, String.class, VehicleType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NscType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NSC", scope = VehicleType.class)
    public JAXBElement<NscType> createVehicleTypeNSC(NscType value) {
        return new JAXBElement<NscType>(_VehicleTypeNSC_QNAME, NscType.class, VehicleType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Jurisdiction", scope = NscType.class)
    public JAXBElement<String> createNscTypeJurisdiction(String value) {
        return new JAXBElement<String>(_AddressTypeJurisdiction_QNAME, String.class, NscType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RegistrationCode", scope = NscType.class)
    public JAXBElement<String> createNscTypeRegistrationCode(String value) {
        return new JAXBElement<String>(_NscTypeRegistrationCode_QNAME, String.class, NscType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BoolYN }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LicenseProduced", scope = DriverLicenseType.class)
    public JAXBElement<BoolYN> createDriverLicenseTypeLicenseProduced(BoolYN value) {
        return new JAXBElement<BoolYN>(_DriverLicenseTypeLicenseProduced_QNAME, BoolYN.class, DriverLicenseType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JurisdictionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Jurisdiction", scope = DriverLicenseType.class)
    public JAXBElement<JurisdictionType> createDriverLicenseTypeJurisdiction(JurisdictionType value) {
        return new JAXBElement<JurisdictionType>(_AddressTypeJurisdiction_QNAME, JurisdictionType.class, DriverLicenseType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Number", scope = DriverLicenseType.class)
    public JAXBElement<String> createDriverLicenseTypeNumber(String value) {
        return new JAXBElement<String>(_VehicleLicenseTypeNumber_QNAME, String.class, DriverLicenseType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ExpiryYear", scope = DriverLicenseType.class)
    public JAXBElement<String> createDriverLicenseTypeExpiryYear(String value) {
        return new JAXBElement<String>(_DriverLicenseTypeExpiryYear_QNAME, String.class, DriverLicenseType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Code", scope = JurisdictionType.class)
    public JAXBElement<String> createJurisdictionTypeCode(String value) {
        return new JAXBElement<String>(_JurisdictionTypeCode_QNAME, String.class, JurisdictionType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CountNumber", scope = CountType.class)
    public JAXBElement<String> createCountTypeCountNumber(String value) {
        return new JAXBElement<String>(_CountTypeCountNumber_QNAME, String.class, CountType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WitnessingOfficerName", scope = EnforcementType.class)
    public JAXBElement<String> createEnforcementTypeWitnessingOfficerName(String value) {
        return new JAXBElement<String>(_EnforcementTypeWitnessingOfficerName_QNAME, String.class, EnforcementType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WitnessingOfficerID", scope = EnforcementType.class)
    public JAXBElement<String> createEnforcementTypeWitnessingOfficerID(String value) {
        return new JAXBElement<String>(_EnforcementTypeWitnessingOfficerID_QNAME, String.class, EnforcementType.class, value);
    }

}
